<Project Sdk="MSTest.Sdk/4.3.3">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>FlashOWare.CommandLine.CliSchema.Tests</AssemblyName>
    <RootNamespace>FlashOWare.CommandLine.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\lib\FlashOWare.CommandLine.CliSchema\FlashOWare.CommandLine.CliSchema.csproj" />
  </ItemGroup>

</Project>
