<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    <CentralPackageVersionOverrideEnabled>true</CentralPackageVersionOverrideEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="FSharp.Core" Version="10.0.100" />
    <PackageVersion Include="Octokit" Version="14.0.0" />
    <PackageVersion Include="System.CommandLine" Version="2.0.11" />
  </ItemGroup>

</Project>
